### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by DominicMaas** [CitiesSkylinesMultiplayer/CSM#115]
There are lots of individual issues related to syncing, going to use this issue to combine everything into a nice and easy to see place. Some of these issues may need to be confirmed.

- [x] Placing coal power plants causes desync issues (when the client places a coal power plant, only the base appears for the host, and it does not make power for the city) #108 
- [x] Sync road and building names. #114 
- [ ] Abandoned buildings are not synced. #101 
- [x] Misc income sync issues. #100 
- [ ] Syncing creation and destruction of citizens. #69 
- [ ] Sync issues with custom mods & assets. #97 
- [x] Sync issue with placing recycling centres. #113 
- [x] Placement of fire department causing desync. #106

**Comment by sedomo** [comment]
@kaenganxt Hello I know you might be busy but any progress on this? Me and my friend tried to play with this mod but the game won't sync at all so he has to keep doing /sync every time I change something.
