### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kaenganxt** [CitiesSkylinesMultiplayer/CSM#152]
This aims to be a vague roadmap for the mod.

- [x] Automatically send over the world on join (allow joining from main menu) [~ End of 2019]
- [x] Improve user experience (player management, better chat, bug fixes) [~End of 2020]
- [ ] Finish syncing all features of the base game (without DLCs) [~ End of 2023]
- [x] Implement modding API so other mods can add multiplayer support through CSM [~ Summer 2021]
- [x] Further improve user experience (Timeout on join, help with firewalls, performance improvements) [~ April 2023]
- [ ] Implement full DLC support [~ 2024]
- [ ] Develop a dedicated server [Future]

(Specific feature progress can be seen in the repo project here: https://github.com/DominicMaas/Tango/projects/1)

**Comment by kaenganxt** [comment]
@DominicMaas Please take a look and tell me if you would change something.

**Comment by DominicMaas** [comment]
I'm happy with this roadmap, thanks!

**Comment by ghpdohmen** [comment]
I think this needs to be updated. It's end of 2020 and most items aren't synced yet

**Comment by kaenganxt** [comment]
Updated the Roadmap

**Comment by sedomo** [comment]
This roadmap might have to be updated again

**Comment by VictorXcraft** [comment]
This mod is bugged and it is not compatible w/ TM:PE
![image](https://user-images.githubusercontent.com/81340759/151022297-c075235f-0815-4ec3-9d64-fc7d72b08b44.png)

**Comment by Levvy055** [comment]
1. The link to project is outdated. 404
2. Let's prepare to move onto . Net 10
